---
title: "PCA"
author: "Wu Qi"
date: "3/3/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#packages:
#install.packages("styler")
library(styler)
library(devtools)
#install.packages("factoextra")
library(factoextra)
install_github("vqv/ggbiplot")
#error: "failed to set default locale"
#solution: system('defaults write org.R-project.R force.LANG en_US.UTF-8') -> restart R
library(ggbiplot)

```



```{r}
#find a better way to group and weight the indices(variables), e.g. principle component

#principle component 

data.pca <- prcomp(final_data[,3:48],center = TRUE,scale. = TRUE)
#centure: whether the variables should be shifted to be zero centered
#scale: whether the variables should be scaled to have unit variance before the analysis takes place
summary(data.pca)  # Importance of components 
str(data.pca)
#You obtain 12 principal components, each of these explains a percentage of the total variation in the dataset.

fviz_eig(data.pca)  # Extract and visualize the eigenvalues/variances of dimensions,Show the percentage of variances explained by each principal component.

fviz_pca_ind(data.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )

#Graph of variables. Positive correlated variables point to the same side of the plot. Negative correlated variables point to opposite sides of the graph.

fviz_pca_var(data.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
ggbiplot(data.pca)

```


```{r}
#Clustering: good and bad district 

#sensitivity analysis: if we change the weight of different index, how is the result gonna change
#calculate the new living Index according to principle component






```
