---
title: "Data Cleaning - Protocol - statistik-berlin-brandenburg-daten"
author: "Malgorzata Olesiewicz"
date: "15 December 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Getting the data
Data from the www.statistik-berlin-brandenburg.de potal (the portal) have been accessed on the 15th of December 2018. As the data cannot be directly downloaded from the potal, they have been copied to csv file (statistik-berlin-brandenburg-daten.csv) and saved on the GitHub repository of the project (<https://github.com/Olesiewitch/SPL-Project/tree/master/data>)
The following Protokol describes the process of data cleaning and merging it into the csv file. As the naming of the original data is in German, the process of data translation is also described.   

### Dirstics

The names and numeration of the Berlin districts have been kept according to the portal standards. 
See : <https://www.statistik-berlin-brandenburg.de/regionales/sg-tabelle-regionales.asp?Kat=7101>

### Population
Data obtained from <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=13003&creg=BBB&anzwer=6>

Original name : Bevölkerung 
English Translation : "Population"
Unit: Thousand
Year: 2017


### District Size
Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=33000&creg=BBB&anzwer=8>

Original name:"Flächennutzung Insgesamt" 
English Translation: District Size
Unit: Ha
Year: 2017

### Residential and traffic surface
Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=33000&creg=BBB&anzwer=8>

Original name:"Siedlungs-und Verkehrs-fläche" 
English Translation: Residential and traffic surface
Unit: Ha
Year: 2017

### Agricultural surface
Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=33000&creg=BBB&anzwer=8>

Original name:"Landwirt-schafts-fläche" 
English Translation: Agricultural surface
Comments: "-" for Mitte has been replaced by 0
Unit: Ha
Year: 2017

### Employment 
Data obtained from <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=13003&creg=BBB&anzwer=6>

Original name: " Davon Erwerbstätige 1000"
English Translation: "Employment per 1K ppl in employment"
Unit: Thousand
Year: 2017

### Unemployment
Data obtained from <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=13003&creg=BBB&anzwer=6>

Original name: "Davon Erwerbslose 1000"
English Translation: "Uneployment"
Unit: Thousand
Year: 2017

### Non-Professional Persons
Data obtained from <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=13003&creg=BBB&anzwer=6>

Original name: "Nichterwerbs-personen"
English Translation: "Non-Professional Persons"
Unit: Thousand
Year: 2017

### Privet Hauseholds
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=12011&creg=BBB&anzwer=5>

Original name: "Haushalte 1000"
English Translation: "Private Hauseholds"
Unit: Thousand
Year: 2017

### Persons/Household
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=12011&creg=BBB&anzwer=5>
Original name: "Personen/Haushalt"
English Translation: "Persons/Household"
Unit: Thousand
Year: 2017

### Schools
Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=21001&creg=BBB&anzwer=5>

Original name: "Schulen"
English Translation: Schools
Unit: Total
Year: Schools year 2017/2018


### Grades
Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=21001&creg=BBB&anzwer=5>

Original name: "Klassen"
Comments: "in Berlin ohne Kurshalbjahre an der gymnasialen Oberstufe"
English Translation: Grades
Unit: Total
Year: Schools year 2017/2018

### Pupils

Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=21001&creg=BBB&anzwer=5>

Original name: "Schüler"
English Translation: Grades
Unit: Total
Year: Schools year 2017/2018

### Pupils/K

Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=21001&creg=BBB&anzwer=5>

Original name: "Schüler je 1000 Einwohner"
English Translation: Pupils/K
Comments: Stichtag 31.12.2017. Berlin: Einwohnerregister, Brandenburg: Fortschreibung des Bevölkerungsstands

Unit: Total
Year: Schools year 2017/2018

### Residential buildings 
Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=31000&creg=BBB&anzwer=0>

Original name: "Wohngebäude einschließlich Wohnheime"
English Translation: Residential buildings 
Comments: Inclusive dormitories
Unit:Total
Year: 2017

### Flats
Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=31000&creg=BBB&anzwer=0>

Original name: "Wohnungen in Wohn- und Nichtwohngebäuden"
English Translation: Flats
Comments: In residential and non-residential buildings
Unit: Total
Year: 2017

### Total living space
Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=31000&creg=BBB&anzwer=0>

Original name: "Wohnfläche insgesamt"
English Translation: Total living space
Unit:1000 m²
Year:2017

### Living space per capita
Data obtained from: <https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=31000&creg=BBB&anzwer=0>

Original name: "Wohnfläche je Einwohner"
English Translation:Living space per capita 
Unit: m²
Year: 2017

### Hotel beds
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=45005&creg=BBB&anzwer=7>

Original name: "Angebotene Betten"
English Translation: Hotel beds 
Unit: Total
Year: 2017

### Tourist guests

Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=45005&creg=BBB&anzwer=7>

Original name: "Gäste"
English Translation: Tourist guests 
Unit: Total
Year: 2017

### Tourist guests

Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=45005&creg=BBB&anzwer=7>

Original name: "Gäste"
English Translation: Tourist guests 
Unit: Total
Year: 2017

### Overnight stays
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=45005&creg=BBB&anzwer=7>

Original name: "Übernachtungen"
English Translation: Overnight stays
Unit: Total
Year: 2017


### Social Help Recipients
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=22001&creg=BBB&anzwer=5>

Original name:Hilfe zum Lebensunterhalt (Kapitel 3) 
English Translation: Social Help Recipients 
Unit: Total
Year: 2017

### Children in daycare 
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=22005&creg=BBB&anzwer=9>

Original name:Betreute Kinder 
English Translation: Children in daycare 
Unit: Total
Year: 1.3.2018

### % Children in daycare under 3 
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=22005&creg=BBB&anzwer=9>

Original name: Betreuungsquote¹ Kinder unter 3
English Translation: % Children in daycare under 3 
Comment: Children in day care per 100 children in the same age group. Population on 31 December 2017
Unit: %
Year: 1.3.2018

### % Children in daycare 3 - under 6 
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=22005&creg=BBB&anzwer=9>

Original name: Betreuungsquote¹ Kinder 3 bis unter 6
English Translation: % Children in daycare 3 - under 6 
Comment: Children in day care per 100 children in the same age group. Population on 31 December 2017
Unit: %
Year: 1.3.2018

### Severely handicapped 
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=22007&creg=BBB&anzwer=10>

Original name: Schwerbehinderte
English Translation: Severely handicapped
Unit: Total
Year: 2017

### Severely handicapped per 1000 inhabitants
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=22007&creg=BBB&anzwer=10>

Original name: Schwerbehinderte je 1000 Einwohner
English Translation:Severely handicapped per 1000 inhabitants 
Unit: Total
Year: 2017


###Companies
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=52001&creg=BBB&anzwer=5>

Original name: "Unternehmen"
English Translation:Companies
Unit: Total
Year: 30.09.2017

###Taxable Revenues
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=52001&creg=BBB&anzwer=5>

Original name:Steuerbarer Umsatz 2016 aus Lieferungen und Leistungen
English Translation:  Taxable Revenues
Comments: from deliveries and benefits
Unit: 1000 €
Year: 30.09.2017

### Bankruptcies
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=52004&creg=BBB&anzwer=7>

Original name: Insolvenzen Insgesamt
English Translation:Bankruptcies  
Unit: Total
Year: 30.09.2017


### Street traffic accidents
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=46002&creg=BBB&anzwer=6>

Original name: Straßenverkehrsunfälle
English Translation: Street traffic accidents
Unit: Total
Year: 2017

### Housing allowance households
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/regionalstatistiken/r-gesamt_neu.asp?Ptyp=410&Sageb=22003&creg=BBB&anzwer=7>
Original name: Wohngeldhaushalte insgesamt
English Translation: Housing allowance households
Unit: Total
Year: 2017

###Senior Members of Sport Clubs 	
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/Statistiken/statistik_SB.asp?Ptyp=700&Sageb=21006&creg=BBB&anzwer=10>
Excel file, Sheet T9 
Original name: Anteil der Mitglieder an Einwohnern in %, 61 und mehr
English Translation:Senior Members of Sport Clubs 
Unit: %
Year: 2018 

###Junior Members of Sport Clubs	
Data obtained from: 
<https://www.statistik-berlin-brandenburg.de/Statistiken/statistik_SB.asp?Ptyp=700&Sageb=21006&creg=BBB&anzwer=10> 
Excel file, Sheet T9 
Original data: Anteil der Mitglieder an Einwohnern in %, bis 6, 7-14, 15-18 
*The data for the three age groups have been merged.*
English Translation: Junior Members of Sport Clubs
Year: 2018
Unit: % 

###Sport Clubs
Data obtained from: <https://www.statistik-berlin-brandenburg.de/Statistiken/statistik_SB.asp?Ptyp=700&Sageb=21006&creg=BBB&anzwer=10>
Excel file, Sheet G3
Original data:  Sportvereine
Year:2018 
Unit: Total Number